server:
  port: 8080

api:
  jph:
    domain: "jsonplaceholder.typicode.com"
    endpoints:
      user: "/users"
      post: "/posts"
      comment: "/comments"


database: 
  postgres: "db_forum"

spring.datasource:
  driverClassName: "org.hibernate.dialect.PostgreSQLDialect"
  url: "jdbc:postgresql://localhost:5432/${database.postgres}"
  username: "postgres"
  password: "Bibuchu#1"

spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update